### ISSUE TITLE
Is it possible to reuse the pre-compiled VM in concurrent environment

### ISSUE THREAD

**Issue by aantono** [d5/tengo#133]
My use-case is to have an external script define the execution logic (data mutation/enhancements) which can happen on concurrent requests... (think about an HTTP server with Middleware mutating request headers, where the logic for mutation is defined by a custom external script).  The server supports multiple requests coming in at once, and for performance reasons I would like to avoid having to instantiate and compile a new VM instance for every request.

Is it possible to have one VM instance be compiled and re-used in a safe concurrent calls environment, or do I have to create new VM per request, as there is possible race condition with `c.Set()` and `c.Get()` mutating the same global variable in the script from concurrent executions.

**Comment by d5** [comment]
Hey, thanks for sharing your use case. 

I was actually working on a similar HTTP-request handling use case where the code is pre-compiled once and re-used multiple times. The only difference I can think of is that it's distributed so the compiled bytecode (binary data) is stored in the databases (e.g. Redis), and, the handler processes always reconstruct the VM from the compiled bytecode. It works really well _(and I'd like to share the project with you when it's ready)_, but, as it builds the VM instance from the binary, it does not use `Script` and `Compiled` but use `Compiler` and `VM` directly. 

That's why I didn't worry about concurrency of re-using `script.Compiled`, but, I agree that it can be very useful if it is thread safe. I will take a look at this and update you later today.

**Comment by d5** [comment]
https://github.com/d5/tengo/pull/134
