### ISSUE TITLE
Run another piece of code after one.

### ISSUE THREAD

**Issue by topxeq** [d5/tengo#137]
Can I run the code line by line or block by block, and keep the variables and other environments?

**Comment by topxeq** [comment]
Thanks for your reply. For example,

```
var code1 = `
a := 3
`

var code2 = `
b := a + 5
`

func main() {

  vm := script.New([]byte(code1))

  vm.Run()

  vm.RunCode([]byte(code2))

  b := vm.Get("b") // expect to be 8
}

```
Is it possible? If yes, I will be able to write something like a interactive shell.

I like this repository. I am going to introduce it in my new book. So I am trying to know more about it...,  and expect more.

**Comment by d5** [comment]
I see. I think you should try Tengo [REPL](https://github.com/d5/tengo/blob/master/docs/tengo-cli.md#tengo-repl) first if you want some interactive shell. And, if so, [this](https://github.com/d5/tengo/blob/master/cmd/tengo/main.go#L188) is where you can start. It uses Parser, Compiler, VM directly instead of using Script. Please let me know.

**Comment by topxeq** [comment]
Yes, I have viewed the runREPL funtion, but everytime in loop it creates a new VM, then compiles the code and runs the code.  I have check the document on godoc.org, too. There is no way to keep the VM state and run another piece of code. Only 3 methods provide: NewVM, run, and abort.

**Comment by d5** [comment]
Well it's because it has to re-compile the input source code (parse+compile) to generate a new bytecode to run in VM. I think that's what you want based on your example code above. 

You can definitely re-use the same VM only if you're simply replacing values of global variables (like `script.Compiled`), but, if you want to run the new source code every time, you definitely need to parse and compile them.

**Comment by topxeq** [comment]
Is it possible to merge the old VM while creating new VM? I think only global variables and functions are necessary to merge.

**Comment by d5** [comment]
Not in the current version at least. It will have to reiterate all bytecode to find/replace global indexes and etc. It's a lot of manual stitching, and, I highly recommend just recompiling if the performance is your concern. It still maintains the "states" by sharing symbol table and globals between compile-run cycles.

**Comment by topxeq** [comment]
Ok, never mind, at least I know the reason now.
