### ISSUE TITLE
json encode bug

### ISSUE THREAD

**Issue by MoonShining** [d5/tengo#268]
https://github.com/d5/tengo/blob/master/stdlib/json/json_test.go

try this test case `testJSONEncodeDecode(t, "1\u001C04")`		

it reports `invalid character 'x' in string escape code`

**Comment by ozanh** [comment]
Hi, here is my quick dirty solution without touching tengo's json scanner. I think current scanner handles `\u` but not `\x` sequences. So, changing tengo's json encoder to use go's `json.Marshal()` instead of `strconv.AppendQuote` for string encoding fix this case, at least tests are ok.
Current https://github.com/d5/tengo/blob/b203f09032cad2123b6e06d6242d7b40686eb4a0/stdlib/json/encode.go#L132-L134
Solution
```go
        case *tengo.String:
		var err error
		b, err = json.Marshal(o.Value)
		if err != nil {
			return nil, err
		}
		// b = strconv.AppendQuote(b, o.Value)
	case *tengo.Time:
```
What do you think?

**Comment by d5** [comment]
For context: main motivation for the custom implementation of JSON (instead of using Go stdlib json module as-is) was mainly the running performance. All Tengo objects have explicitly defined value types so there were some performance gains by skipping all reflection related code path in the standard library.

Obviously an easier solution here is just to use the Go implementation. But I still want to try and see if this escaping issue can be easily fixed. Unfortunately I simply don't have time to look into this at the moment.

**Comment by ozanh** [comment]
We can port go's string to json encoder function directly so there will no reflection penalty. I can make it if you like. Other json libraries also use port of go implementation for string encoding.

**Comment by d5** [comment]
Contribution is always welcomed!
