### ISSUE TITLE
Enable relative imports

### ISSUE THREAD

**Issue by maichmueller** [d5/tengo#280]
Importing a module `tre.tengo` 
```
fun := func(a) {
  return a
}

tre := {
  fun: fun
}
export tre
```
in another tengo script `due.tengo` (both files are in the same folder) 
```
tre := import(`tre`)

funcy := func(a) {
  return tre.fun(a)
}

due := {
  funcy: funcy
}
export due
```
throws an error, when tengo is invoked as CLI from another directory, e.g. the parent folder :

>Compile Error: module file read error: open tre.tengo: no such file or directory
        at due.tengo:2:8

It works fine however when tengo is invoked from within the folder. This leads me to suspect the import is done relative to the working directory. Relative imports feel more intuitive though, or am I wrong. Is there already a way to import relative to another file?

**Comment by d5** [comment]
In the current implementation, all import paths are determined based on the working directory (like bash). But I'm open to other options. @geseq @ozanh

**Comment by geseq** [comment]
I’m open to relative imports. I can imagine use cases were relative imports would be more suitable than what we have now.

**Comment by ozanh** [comment]
While using bash, changing current working directory to call other scripts with relative imports make me frustrated. Python has sys.path to resolve imports, but it is a luxury for now. Default behavior can be setting tengo's working directory to script's dir within tengo executable for both run and compile only options.

**Comment by d5** [comment]
Just to make sure I understand it correctly. 

```
- dir1
  - file1.tengo
  - file2.tengo
  - dir2
    - file3.tengo
    - dir3
      - file4.tengo
```

dir1/file1.tengo:
```golang
import("file2") // or "./file2"
```

dir1/file2.tengo
```golang
import("dir2/dir3/file4") // or "./dir2/dir3/file4"
```

dir2/file4.tengo
```golang
import("../file3")
```

Running `dir1/file1.tengo` would import the other 3 files using such relative paths (file1 -> file2 -> file4 -> file3)?

A couple of things:
- What if the first (root) script is not a physical Tengo file, but a Tengo code inside Go? Should we use the current working directory for `import` statements in that script?
- We will have to **normalize** those paths so we can detect/prevent the cyclic imports correctly.

**Comment by maichmueller** [comment]
Hey thanks for your quick answers everyone!
@d5 I think the import you suggested is correct. That's how I would expect it. That would allow to write a form of package for the tengo code.

Regarding tengo in go: One could go for working directory relation or again relative relation to the calling go file I guess. there are benefits and disadvantages to both. However, in a go package id assume that 'relative to the working directory' is more consistent as the tengo code may then be sent around within Go pkgs without changing the context of the import.

**Comment by ozanh** [comment]
Hi, I've worked a little, please check this [patch](https://gist.github.com/ozanh/b2a996d9504831b7734d3d7cf7c04e9a)
It resolves file import paths in Compiler and in non-file source modules you need to write import paths considering what is initially set with `*Script.SetImportPath()` and resolves relative import paths. In tengo executable it sets the executable's current working dir to script file's dir and then the rest is same. Since every path is absolute it can detect cyclic imports. Not a complete solution though! Please review it.

**Comment by d5** [comment]
Haha. Why don't you create a PR? @ozanh

**Comment by idoall** [comment]
I need this function very much. I also meet this requirement when I write a lot of tengo modules

**Comment by maichmueller** [comment]
Hi, I think the fix didn't work. The error persists:
Both files (as they are in the initial post) are in the directory /home/michael/GitHub/tengo. Calling tengo from outside the folder gives:

> tengo tengo/due.tengo 
Compile Error: module file read error: open /home/michael/GitHub/tre.tengo: no such file or directory
        at due.tengo:2:8

From inside the folder it works.

**Comment by ozanh** [comment]
Hi @maichmueller , if you test new feature with tengo CLI  please check new command line flag `-resolve`. That enables relative imports. From Go, you should call `Script.SetImportDir()` with a path to enable it. If you do all these things and it still does not work, then we have a big problem.
In version 3, this feature will probably be the default behavior. Sorry it is not documented due to time constraints and urgent bugs.

**Comment by maichmueller** [comment]
Works fine with the flags. Thanks for the quick fixes and the great work!
