### ISSUE TITLE
Function re-assignment in another function causes SIGSEGV in Tengo VM

### ISSUE THREAD

**Issue by ganehag** [d5/tengo#314]
The following Tengo code:

```golang
func1 := func(a, b) {
    return a * b
}

func2 := func() {
    test := test(1, 2)
}

func2()
```

While completely bonkers (re-assigning a function), produces a SIGSEGV, which should not happen.

```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x52eb39]

goroutine 1 [running]:
github.com/d5/tengo/v2.(*VM).run(0xc000180000)
	/home/runner/work/tengo/tengo/vm.go:542 +0x2ac9
github.com/d5/tengo/v2.(*VM).Run(0xc000180000, 0xc000180000, 0x400)
	/home/runner/work/tengo/tengo/vm.go:77 +0xcf
main.CompileAndRun(0xc0001026f0, 0xc000152000, 0x5e, 0x25e, 0xc0001163d0, 0xc, 0x0, 0xc000104120)
	/home/runner/work/tengo/tengo/cmd/tengo/main.go:144 +0x1d0
main.main()
	/home/runner/work/tengo/tengo/cmd/tengo/main.go:83 +0x420
```

I stumbled upon this by happenstance as a result of a typo in my code.

**Comment by mccolljr** [comment]
> ```go
> func1 := func(a, b) {
>     return a * b
> }
> 
> func2 := func() {
>     test := test(1, 2)
> }
> 
> func2()
> ```

Just to clarify, is the body of `func2` supposed to be `func1 := func1(1,2)`? Looks like maybe a copy-paste error

**Comment by ganehag** [comment]
Yes, my mistake when I changed it before posting. Both; `test := test(1,2)` and `func1 := func1(1,2)` will cause a SIGSEGV.

**Comment by ozanh** [comment]
Hi, it can be fixed by moving symbol table name resolution after right hand side expression compilation and small symbol table changes. If @d5 accepts I can create a PR to fix it.

**Comment by d5** [comment]
yes please

**Comment by ozanh** [comment]
It seems a little tricky. Moving `c.symbolTable.Resolve(ident)` below the right hand side (RHS) compilation is more idiomatic but this time following code does not work (unresolved reference);
```
one := func() { one = 1; return one }; out = one()
```
This must be rewritten as below to make it work.
```
one := undefined; one = func() { one = 1; return one }; out = one()
```
I have revised all failed tests due to this resolution error in 5 minutes BUT this is a language change. 
OR; 
We can check the error returned from RHS compilation and define the variable as usual not to change current usage to support both cases.
What do you think?

**Comment by geseq** [comment]
It makes sense that the first example would return unresolved reference, doesn’t it?

**Comment by d5** [comment]
Wow. All 3 main contributors are commenting on this. I will take a look at this as well!

**Comment by d5** [comment]
It looks like the issue here is the symbol resolution of local variables that are not assigned. 

This code

```
(func() {
    fn := fn()
})()
```

compiles to:

```
        [Compiled Constants]
        
        [  0] (Compiled Function|0xc00000e708)
             0000 GETL    0    
             0002 CALL    0     0    
             0005 DEFL    0    
             0007 RET     0    
        
        [Compiled Instructions]
        
        0000 CONST   0    
        0003 CALL    0     0    
        0006 POP    
        0007 SUSPEND
```

And

```
fn := func() {}	
(func() {
    fn := fn()
})()
```

compiles to 

```
        [Compiled Constants]
        
        [  0] (Compiled Function|0xc00000e708)
             0000 RET     0    
        [  1] (Compiled Function|0xc00000e710)
             0000 GETL    0    
             0002 CALL    0     0    
             0005 DEFL    0    
             0007 RET     0    
        
        [Compiled Instructions]
        
        0000 CONST   0    
        0003 SETG    1    
        0006 CONST   1    
        0009 CALL    0     0    
        0012 POP    
        0013 SUSPEND
```

In both scenario, symbol `fn` in the right-hand side of `fn := fn()` (inside the function) should be a compile error _(the first code; unresolved reference)_ or should refer to a global variable `fn` _(the second code)_. But instead it's trying to reference the `fn` in the left-hand side _(that's not yet assigned)_.

The Tengo compiler has this [non-intuitive behavior](https://github.com/d5/tengo/blob/master/compiler.go#L423-L471) so it can support the local recursive functions such as

```
func() {
    foo := func(x) {
        // ..
        return foo(x-1)
    }
}
```

I will think about the solutions here, but, it should be something like... **do not resolve a "local" variable that's not assigned if they're in the same depth**.

**Comment by d5** [comment]
See https://github.com/d5/tengo/pull/316 and let me know what you guys think.
