### ISSUE TITLE
FFI?

### ISSUE THREAD

**Issue by prologic** [d5/tengo#49]
Been observing new issues like #44 #45 and #46 

Instead of duplicating the Go standard library in Tengo; Why not crate an [FFI](https://en.wikipedia.org/wiki/Foreign_function_interface)? This has the added advantage of allowing users to build new modules of anything they need that isn't already part of the Tengo standard library (_exposing Go standard library modules/functions_).

**Comment by d5** [comment]
Totally. I love to have something like that. It's not worth the efforts duplicating all Go stdlib for very obvious reasons. I'm still trying to figure out the best way of doing it _(and am always open to any suggestions)_, but, at the moment, I decided to focus (prioritize) more on extensibility/interoperability (e.g. operator overloading, callable objects, indexable objects) so it can be more easily embedded to Go code, rather than trying to make it a full standalone language, in which case having standard library and more language features (e.g. concurrency) become more important. For me, currently the real challenge is to maintain the flexibility and the performance, but, again, I'd appreciate any ideas/proposals on this matter.

Btw, those modules (os, math, regex, etc) are not final and very experimental. I'm adding them only because they're most commonly used ones in typical scripting use cases (although I don't have any data to support my assumption 😛). Does this make sense?
