### ISSUE TITLE
Question: Hide helpers in modules?

### ISSUE THREAD

**Issue by tisba** [d5/tengo#66]
I found the module documentation in https://github.com/d5/tengo/blob/master/docs/tutorial.md (not sure if there is another document). I was wondering, if and how I can "hide" module-internal stuff, like helper functions etc.

> Basically, import expression returns all the global variables defined in the module as a Map-like value.

If all "global defined" variables in a module are exported, there is currently no way to hide module internals, correct?

I was also wondering, what your thought process was for doing it that way, compared e.g. to mark variables as exported.

btw: Thank you a lot for tengo. I'm not using it for anything else then playing around, but I'm learning a lot by trying to understand how you build it! 💕

**Comment by d5** [comment]
You're correct. Currently there's no way to hide values _(or selectively choose values to export)_ when exporting the code as a module. It is mostly because I wanted to keep things simple as much as possible _(at least for now)_, but, at the same time, I also wanted to make scripts import-able to other scripts with no _(or little)_ changes. For example, let's say I have a script `script1` that I use in my FSM implementation _(for conditions, entry/exit functions, etc)_, but, later I may want to use some of its functions in another script by simply doing `import("script1")`. That said, I may add something different in the future if there's a strong reason 😃

**Comment by tisba** [comment]
IMO having a clear and explicit API to helps a lot in order to prevent clutter. But I do fully understand your point about keeping it as simple as possible!

**Comment by d5** [comment]
@tisba: I was trying to fix some module-related issues, and, I decided to make 'export' more explicit. As of [v1.3.0](https://github.com/d5/tengo/releases/tag/v1.3.0), one needs to use `export` statement to export a value. Just FYI.
